Web_projects/Encuesta-/app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    from .routes import main
    app.register_blueprint(main)
    return app

Web_projects/Encuesta-/app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from datetime import datetime
import csv
import re
main = Blueprint('main', __name__)
porcentajes = []
porcentajes_lista = []

@main.route('/')
def index():
    datos = obtener_datos_desde_csv()
    return render_template('formulario.html', datos=datos)

@main.route('/index')
def volver_index():
    return render_template('formulario.html')

@main.route('/procesar_formulario', methods=['POST'])
def procesar_formulario():
    ide = generar_id()
    print(ide)

    datos_actualizados = [ide, request.form['nombre'], request.form.get('pregunta-1'),
                          request.form.get('pregunta-2'), request.form.get('pregunta-3'),
                          request.form.get('pregunta-4'), request.form.get('pregunta-5'),
                          request.form.get('pregunta-6'), request.form.get('pregunta-7'),
                          request.form.get('pregunta-8'), request.form.get('pregunta-9'),
                          request.form['pregunta-10']]

    porcen = analizar(datos_actualizados)
    print(porcen)
    print(f"{sacar_porcentajes(porcen)}")
    guardar_datos_en_csv(datos_actualizados)
    ordenar_datos()
    return redirect(url_for('main.index'))

@main.route('/resultados')
def resultados():
    datos = obtener_datos_desde_csv()
    porcentajes = obtener_porcentajes_desde_archivo()
    return render_template('respuesta.html', datos=datos, porcentajes=porcentajes)

@main.route('/ver_porcentajes')
def ver_porcentajes():
    porcentajes = obtener_porcentajes_desde_archivo()
    return render_template('porcentajes.html',porcentajes=porcentajes)

@main.route('/borrar_registros')
def borrar_registros():
    borrar_registros()
    return render_template('respuesta.html') 

def generar_id():
    ruta = 'app/data/id.txt'
    with open(ruta, "r+") as file:
        ide = int(file.read().strip() or 0)
        ide += 1
        file.seek(0)
        file.write(str(ide))
        file.truncate()
    return ide


def guardar_datos_en_csv(datos):
    with open('app\data\datos.csv', 'a', newline='', encoding='utf-8') as archivo:
        escritor_csv = csv.writer(archivo)
        escritor_csv.writerow(datos)

def obtener_datos_desde_csv():
    with open('app/data/datos.csv', 'r', encoding='utf-8') as archivo:
        lector_csv = csv.reader(archivo)
        return list(lector_csv)


def analizar(datos):
    porcentajes = []

    def separar_si_no(n, iden, i, opc):
        print(f"Entró contenedor-{n}")
        ruta = f"app/data/contadores-{n}.csv"
        print(ruta)
        total = float(100)
        with open(ruta, 'r') as file:
            reader = csv.reader(file)
            data = list(reader)[0]
            num = int(i)

            data[num - 1] = str(int(data[num - 1]) + 1)
            valor = data[num - 1]
            print(valor)

            porcentaje = int(valor) / int(iden) * 100
            restante = round((total - float(porcentaje)), 2)
            porcentaje = round(porcentaje, 2)
            restante = round(restante, 2)

            if opc == "si":
                porcentajes.append(
                    f"P{num} {opc.upper()} = {porcentaje}%  NO = {restante}%")
            else:
                porcentajes.append(
                    f"P{num} {opc.upper()} = {porcentaje}%  SI = {restante}%")

        with open(ruta, 'w', newline='') as files:
            writer = csv.writer(files)
            writer.writerow(data)

    ult = datos
    iden = ult[0]
    for i in range(len(ult)):
        if ult[i] == "si" or ult[i] == "diariamente" or ult[i] == "mensualmente" or ult[i] == "semanalmente" or ult[i] == "aveces":
            contadores = 1
            opc = "si"
            separar_si_no(contadores, iden, i, opc)

        else:
            contadores = 2
            opc = "no"
            separar_si_no(contadores, iden, i, opc)

    print(iden)
    ordenar_porcentajes(porcentajes)

    return porcentajes


def ordenar_datos():
    with open('app/data/datos.csv', 'r', encoding='utf-8') as archivo:
        lector_csv = csv.reader(archivo)
        info = list(lector_csv)
    with open('app/data/datos.txt', "w", encoding="utf-8") as archivo:
        for i in range(len(info)):
            archivo.write(
                f'''\nPERSONA ID {i + 1}: {info[i][0]}\nNOMBRE TIENDA: {info[i][1]}\nPREGUNTA 1: {info[i][2]}\nPREGUNTA 2: {info[i][3]}\nPREGUNTA 3: {info[i][4]}\nPREGUNTA 4: {info[i][5]}\nPREGUNTA 5: {info[i][6]}\nPREGUNTA 6: {info[i][7]}\nPREGUNTA 7: {info[i][8]}\nPREGUNTA 8: {info[i][9]}\nPREGUNTA 9: {info[i][10]}\nPREGUNTA 10:  {info[i][11]}\n''')  

def obtener_porcentajes_desde_archivo():
    with open('app/data/porcentajes.txt','r',encoding="utf-8") as archivo:
        porcentajes=archivo.readlines()
    return porcentajes

def ordenar_porcentajes(porcentajes):
    
    with open('app/data/porcentajes.txt', "w", encoding="utf-8") as archivo:
        for i in range(len(porcentajes)):
            archivo.write(f'''{porcentajes[i]}\n''')
    return porcentajes

def sacar_porcentajes(porcen):
         #Abrir el archivo y leer cada línea
        for linea in porcen:
            resultado = re.search(r'\b(\d+)\b', linea)
        if resultado:
            porcentaje_int = int(resultado.group())
            porcentajes_lista.append(porcentaje_int)
         # Imprimir la lista de porcentajes
        return porcentajes_lista

def borrar_registros():
    # Listas de datos y rutas de archivos
    listas = [[0]*12, [0]*12]  # Dos listas con 12 ceros
    archivos = ['app/data/contadores-1.csv', 'app/data/contadores-2.csv']

    # Borrar el contenido de los archivos de contadores
    for i, archivo in enumerate(archivos):
        with open(archivo, 'w', encoding='utf-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(listas[i])

    # Borrar el contenido del archivo datos.csv
    with open('app/data/datos.csv', 'w', encoding='utf-8', newline='') as datos_csv:
        pass  # Al abrir en modo escritura, ya borra el contenido
    with open('app/data/datos.txt','w',encoding='utf-8') as datos_txt:
        datos_txt.write('')
    with open('app/data/id.txt','w',encoding='utf-8') as identificacion:
        identificacion.write('0')
    with open('app/data/porcentajes.txt','w',encoding='utf-8') as porcentajes:
        porcentajes.write('')
    print('archivos formateados con éxito')

Web_projects/Encuesta-/app/templates/formulario.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encuesta</title>
    <link rel="stylesheet" href="{{ url_for('static', filename ='css/styles.css') }}">
    <script>
        // Desactivar la funcionalidad de retroceso
        history.pushState(null, null, document.URL);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.URL);
        });
    </script>
</head>
<body>
    <header>
        <a href="{{url_for('main.index')}}"><img src="{{ url_for('static', filename ='images/Marvy_Shopmarket.png') }}" alt="Icono Marvy Shopmarket" class="icono-m"></a>
        <h1>Encuesta</h1>
        <a href="{{url_for('main.index')}}"><img src="{{ url_for('static', filename ='images/SENA.png') }}" alt="Sena icono" class="icono-m"></a>
        
    </header>

    <div class="obj">
        <div class="content">
            <h2>Objetivo:</h2>
            <div class="objetive">
                <p>Esta encuesta es realizada a 50  tiendas de barrio de la ciudad de Pamplona, Norte de Santander, por los aprendices de ÁNALISIS Y DESARROLLO DE SOFTWARE del CENTRO PARA EL DESARROLLO RURAL Y MINERO (CEDRUM) SENA. Lo anterior con la finalidad de recolectar información, y poder establecer los requisitos funcionales y no funcionales de la nueva aplicación "MARVY SHOPMARKET" que busca apoyar a los tenderos, de la mano de esta herramienta digital, en actividades relacionadas con la gestión de sus ventas y el control de sus inventarios. </p>
            </div>
        </div>
    </div>

    <div class="main">
        <form method="POST" action="{{ url_for('main.procesar_formulario') }}">

            <article>
                <label for="nombre">Nombre de la tienda</label>
                <input name="nombre" id="nombre" type="text">
            </article>
            <article>
                <label for="pregunta-1">Pregunta 1: ¿Utiliza su tienda algun método digital para registrar la información de sus ventas, proveedores y/o productos?  </label>
                <label><input name="pregunta-1" id="pregunta-1" value="si" type="radio">Si</label>
                <label><input name="pregunta-1" id="pregunta-1" value="no" type="radio">No</label>
            </article>
            <article> 
                <label for="">Pregunta 2: ¿Utiliza su tienda algún metodo tradicional (cuaderno, lapicero, hojas de calculo, etc) para registrar la información de sus ventas, proveedores y/o productos? </label>
                <label><input name="pregunta-2" id="pregunta-2" value="si" type="radio">Si</label>
                <label><input name="pregunta-2" id="pregunta-2" value="no" type="radio">No</label>
            </article>
            <article>
                <label for="">Pregunta 3: ¿Lleva un presupuesto y un control de su inventario?</label>
                <label><input name="pregunta-3" id="pregunta-3" value="diariamente" type="radio">Si, diariamente</label>
                <label><input name="pregunta-3" id="pregunta-3" value="semanalmente" type="radio">Si, semanalmente</label>
                <label><input name="pregunta-3" id="pregunta-3" value="mensualmente" type="radio">Si, mensualmente</label>
                <label><input name="pregunta-3" id="pregunta-3" value="aveces" type="radio">Si, A veces</label>
                <label><input name="pregunta-3" id="pregunta-3" value="no" type="radio">No</label>
            </article>
            <article>
                <label for="">Pregunta 4: ¿Realiza informes de ventas y/o recibos a los clientes y proveedores de su tienda?  </label>
                <label><input name="pregunta-4" id="pregunta-4" value="si" type="radio">Si</label>
                <label><input name="pregunta-4" id="pregunta-4" value="no" type="radio">No</label>
            </article>
            
            <article>
                <label for="">Pregunta 5: Del 1 al 10 ¿qué tan seguro se siente con el método que utiliza actualmente su tienda con respecto a la preservación e integridad de los datos? </label>
                <label><input name="pregunta-5" id="pregunta-5" value="1" type="radio">1</label>
                <label><input name="pregunta-5" id="pregunta-5" value="2" type="radio">2</label>
                <label><input name="pregunta-5" id="pregunta-5" value="3" type="radio">3</label>
                <label><input name="pregunta-5" id="pregunta-5" value="4" type="radio">4</label>
                <label><input name="pregunta-5" id="pregunta-5" value="5" type="radio">5</label>
                <label><input name="pregunta-5" id="pregunta-5" value="6" type="radio">6</label>
                <label><input name="pregunta-5" id="pregunta-5" value="7" type="radio">7</label>
                <label><input name="pregunta-5" id="pregunta-5" value="8" type="radio">8</label>
                <label><input name="pregunta-5" id="pregunta-5" value="9" type="radio">9</label>
                <label><input name="pregunta-5" id="pregunta-5" value="10" type="radio">10</label>
            </article>
            <article>
                <label for="">Pregunta 6: Del 1 al 10 ¿qué tan eficiente calificaría el método para registrar la información de ventas, productos y/o proveedores de su tienda? </label>
                <label><input name="pregunta-6" id="pregunta-6" value="1" type="radio">1</label>
                <label><input name="pregunta-6" id="pregunta-6" value="2" type="radio">2</label>
                <label><input name="pregunta-6" id="pregunta-6" value="3" type="radio">3</label>
                <label><input name="pregunta-6" id="pregunta-6" value="4" type="radio">4</label>
                <label><input name="pregunta-6" id="pregunta-6" value="5" type="radio">5</label>
                <label><input name="pregunta-6" id="pregunta-6" value="6" type="radio">6</label>
                <label><input name="pregunta-6" id="pregunta-6" value="7" type="radio">7</label>
                <label><input name="pregunta-6" id="pregunta-6" value="8" type="radio">8</label>
                <label><input name="pregunta-6" id="pregunta-6" value="9" type="radio">9</label>
                <label><input name="pregunta-6" id="pregunta-6" value="10" type="radio">10</label>
            </article>
            </article>
            <article>
                <label for="">Pregunta 7: ¿Sabe Usted qué es software? </label>
                <label><input name="pregunta-7" id="pregunta-7" value="si" type="radio">Si</label>
                <label><input name="pregunta-7" id="pregunta-7" value="no" type="radio">No</label>
            </article>
            <article>
                <label for="">Pregunta 8: ¿Estaría Usted interesado en implementar una solución tecnológica para registrar las ventas, proveedores y productos de su tienda?</label>
                <label><input name="pregunta-8" id="pregunta-8" value="si" type="radio">Si</label>
                <label><input name="pregunta-8" id="pregunta-8" value="no" type="radio">No</label>
            </article>
            <article>
                <label for="">Pregunta 9: ¿Cree que obtendría un beneficio al implementar un software que apoye los procesos en su tienda?</label>
                <label><input name="pregunta-9" id="pregunta-9" value="si" type="radio">Si</label>
                <label><input name="pregunta-9" id="pregunta-9" value="no" type="radio">No</label>
            </article>
            <article>
                <label for="">Pregunta 10: ¿Qué caracteristicas le gustaria que tuviera este software para tiendas como la de Usted?</label>
                <textarea name="pregunta-10" id="pregunta-10" cols="30" rows="10"></textarea>
            </article>
            <article class="btn">
                <input type="submit" name="btn" id="btn" value="Enviar">
            </article>
            
        </form>
        <a class="btn-obj" href="{{url_for('main.resultados')}}">Ver registros</a>
    </div>
    <div class="obj-2">
        <div class="content-2">
            <h2>Politicas de privacidad:</h2>
            <div class="objetive">
                <p>Esta encuesta es realizada a 50  tiendas de barrio de la ciudad de Pamplona, Norte de Santander. Lo anterior con la finalidad de recolectar información acerca de la gestión de ventas y control de inventarios de las mismas, y poder establecer los requisitos funcionales y no funcionales de la nueva aplicación "MARVY SHOPMARKET" que busca apoyar a los tenderos en esos procesos de la mano de esta herramienta digital segura, intuitiva, eficiente para agilizar los mismos. </p>
            </div>
        </div>
    </div>
</body>
</html>

Web_projects/Encuesta-/app/templates/grafico_pastel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gráfico de Pastel</title>
</head>
<body>
    <img src="data:image/png;base64,{{ img_base64 }}" alt="Gráfico de Pastel">
</body>
</html>

Web_projects/Encuesta-/app/templates/porcentajes.html
<!-- templates/porcentajes.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Porcentajes</title>
    <link rel="stylesheet" href="{{ url_for('static', filename ='css/styles.css') }}">
    <script>
        // Desactivar la funcionalidad de retroceso
        history.pushState(null, null, document.URL);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.URL);
        });
    </script>
</head>
<body class="body3">
    <!-- <header class="header2">
        <a href="{{url_for('main.resultados')}}"><img src="{{ url_for('static', filename ='images/flecha-izquierda.png') }}" alt="Icono Marvy Shopmarket" class="icono-m"></a>
        <h1>Porcentajes</h1>
        <a href="{{url_for('main.resultados')}}"><img src="{{ url_for('static', filename ='images/SENA.png') }}" alt="Sena icono" class="icono-m"></a>
        
    </header>
    <div class="Marvy_Shopmarket" style='background-image: url("{{ url_for('static', filename ='images/ilusion.gif') }}"); background-repeat: no-repeat;background-position: center;background-size: cover;'>
        <img src="{{ url_for('static', filename ='images/Marvy_Shopmarket.png') }}" alt="Icono Marvy Shopmarket" class="icono-x">
    </div> -->
    <div class="container">
        <div class="content">
            <div class="header" style="background-image: linear-gradient(rgb(17, 17, 17),#262626,rgb(7, 7, 7)); padding: 2%; display: flex;">
                <a href="{{url_for('main.resultados')}}"><img src="{{ url_for('static', filename ='images/flecha-izquierda.png') }}" alt="Icono Marvy Shopmarket" class="icono-m"></a>
                <h2 style="width: 100%; text-align: center; padding: 0%;">ANALISIS ESTADISTICO</h2>
            </div>
            
            <ul class="list">
            {% for porcentaje in porcentajes %}
                <li class="list-e"><p>{{ porcentaje }}</p></li>
            {% endfor %}
            </ul>
        </div>
        
    </div>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

Web_projects/Encuesta-/app/templates/respuesta.html
<!-- templates/formulario.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registros</title>
    <link rel="stylesheet" href="{{ url_for('static', filename ='css/styles.css') }}">
    <script>
        // Desactivar la funcionalidad de retroceso
        history.pushState(null, null, document.URL);
        window.addEventListener('popstate', function () {
            history.pushState(null, null, document.URL);
        });
    </script>
</head>
<body class="body2">
<div class="contenedor">
    <header class="header2">
        <a href="{{url_for('main.index')}}"><img src="{{ url_for('static', filename ='images/flecha-izquierda.png') }}" alt="Icono Marvy Shopmarket" class="icono-m"></a>
        <h1>Registro de encuestas</h1>
        <a href="{{url_for('main.index')}}"><img src="{{ url_for('static', filename ='images/SENA.png') }}" alt="Sena icono" class="icono-m"></a>
        
    </header>
    <!-- <div class="Marvy_Shopmarket" style='background-image: url("{{ url_for('static', filename ='images/ilusion.gif') }}"); background-repeat: no-repeat;background-position: center;background-size: cover; background-attachment:fixed;'>
        <img src="{{ url_for('static', filename ='images/Marvy_Shopmarket.png') }}" alt="Icono Marvy Shopmarket" class="icono-x">
    </div> -->
    <div class="botons">
        
        <div class="content">
            <a href="{{ url_for('main.borrar_registros') }}" class="btn-2">Borrar registros </a>
            <a href="{{url_for('main.ver_porcentajes')}}" class="btn-3">Analisis estadistico</a>
            
        </div>
        <ul >
            <li>P1: ¿Utiliza su tienda algun método digital para registrar la información de sus ventas, proveedores y/o productos?</li>
            <li>P2: ¿Utiliza su tienda algún metodo tradicional (cuaderno, lapicero, hojas de calculo, etc) para registrar la información de sus ventas, proveedores y/o productos?</li>
            <li>P3: ¿Lleva un presupuesto y un control de su inventario?</li>
            <li>P4: ¿Realiza informes de ventas y/o recibos a los clientes y proveedores de su tienda? </li>
            <li>P5: Del 1 al 10 ¿qué tan seguro se siente con el método que utiliza actualmente su tienda con respecto a la preservación e integridad de los datos?</li>
            <li>P6: Del 1 al 10 ¿qué tan eficiente calificaría el método para registrar la información de ventas, productos y/o proveedores de su tienda?</li>
            <li>P7: ¿Sabe Usted qué es software?</li>
            <li>P8: ¿Estaría Usted interesado en implementar una solución tecnológica para registrar las ventas, proveedores y productos de su tienda?</li>
            <li>P9: ¿Cree que obtendría un beneficio al implementar un software que apoye los procesos en su tienda?</li>
            <li>P10: ¿Qué caracteristicas le gustaria que tuviera este software para tiendas como la de Usted?</li>
        </ul>
    </div>
    
    <div class="contenido">
    <div class="resultados">
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>p1</th>
                <th>p2</th>
                <th>p3</th>
                <th>p4</th>
                <th>p5</th>
                <th>p6</th>
                <th>p7</th>
                <th>p8</th>
                <th>p9</th>
                <th>p10</th>
            </tr>
            {% for fila in datos %}
            <tr>
                {% for valor in fila %}
                <td>{{ valor }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <div class="container-2">
            <div class="content">
                <ul class="list">
                    <h2 style="padding: 3%; width: 100%; text-align: center; margin-top: 0%;">Porcentaje de respuesta por pregunta</h2>
                {% for porcentaje in porcentajes %}
                    <li class="list-e"><p>{{ porcentaje }}</p></li>
                {% endfor %}
                </ul>
            </div>
            
        </div>
        
    </div>
    <!-- <script src="{{ url_for('static', filename='script.js') }}"></script> -->
    <!-- Tu formulario y otros elementos aquí -->
    <!-- Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque suscipit, adipisci rerum perferendis eum, nemo iste tempore totam placeat cumque, harum quis. Blanditiis ab dignissimos nesciunt saepe aliquid consequatur non. -->
    </div>
    
</div>
</body>
</html>